language: bash

jobs:
  include:
    - script: bash test.sh
    - stage: deploy
      script: skip
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        file: "bash_agile.sh"
        on:
          tags: true
